default: &default
  adapter: mysql2
  encoding: utf8mb4
  charset: utf8mb4
  collation: utf8mb4_general_ci
  pool: 5
  username: root
  password:
  host: db
  timeout: 5000

development:
  <<: *default
  database: raisl_app_development

test:
  <<: *default
  database: rails_app_test
